name: Build and release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ios:
    name: Build and release
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2

      - name: Get secret files
        env:
          GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
        run: |
          git clone "https://github:$GITLAB_SECRET@git.imxieyi.com/xieyi/wakutg-build.git"
          cp -r wakutg-build/* .
          ls -lah

      - name: Clone Telegram-iOS
        run: |
          git clone --depth 1 https://github.com/TelegramMessenger/Telegram-iOS.git
          cd Telegram-iOS
          
      - name: Build and upload
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        run: |
          export TG_IOS_ROOT="$(pwd)/Telegram-iOS"
          export BAZEL_CACHE="$(pwd)/bazel-cache"
          ./build.sh
