name: Build and release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_ios:
    name: Build and release
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2

      - name: Install the Apple certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Get secret files
        env:
          GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
        run: |
          git clone "https://github:$GITLAB_SECRET@git.imxieyi.com/xieyi/wakutg-build.git"
          cp -r wakutg-build/* .
          ls -lah

      - name: Clone Telegram-iOS
        run: |
          git clone --depth 1 https://github.com/TelegramMessenger/Telegram-iOS.git
          cd Telegram-iOS
          
      - name: Download iOS Platform
        run: xcodebuild -downloadPlatform iOS -buildVersion 18.2
          
      - name: Build and upload
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        run: |
          export TG_IOS_ROOT="$(pwd)/Telegram-iOS"
          export BAZEL_CACHE="$(pwd)/bazel-cache"
          ./build.sh

